// This file is autogenerated. Changes will be overwritten.
#include "CCOZUX6ICW/moc_AccidentList.cpp"
#include "CCOZUX6ICW/moc_Accidents.cpp"
#include "CCOZUX6ICW/moc_AdminMain.cpp"
#include "CCOZUX6ICW/moc_ObjectTypeAdministration.cpp"
#include "CCOZUX6ICW/moc_RegisterAccidentDialog.cpp"
#include "CCOZUX6ICW/moc_RoleManagment.cpp"
#include "CCOZUX6ICW/moc_UsersList.cpp"
